### PR TITLE
RPI PPTT

### PR DESCRIPTION
**Pull request by jlinton**
This should be a corrected pull, it was missing the build changes. 

Its also got a lot of stuff in front of it which is in the mainline edk2 repos but not in the master repo here.

### CODE REVIEW

**Comment by pbatard** [comment]
Just a hint on how to properly create a pull request (assuming that you have admin access to this repo, which you do):

0. Make sure you add something like:  
```
[remote "upstream"]
	url = https://github.com/tianocore/edk2-platforms.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```
in your `.git\config`.
1. After making sure you're on the `master` branch locally, pull from `upstream` so that your `pftf/edk2-platform` is up to date with mainline
2. Push to `master`, so that this repo gets updated.
3. Create the PR.

Anybody with admin access can update this repo, so you don't have to wait for someone else to do it if you want to submit a PR. Especially, now that we are in a position where we can submit straight to `edk2-devel`, I personally don't have much plan to keep this repo in sync, as I very much prefer skipping pftf altogether and just send commits to `edk2-devel` for review (coz doing a private review before the formal review seems a bit counter productive IMO, especially for a small patchset).

**Comment by jlinton** [comment]
Yah, I wondered whether I should attempt to update master to clear out all those commits.

What I'm hearing is you just want it pushed to a local branch you can pick it up?

**Comment by pbatard** [comment]
> What I'm hearing is you just want it pushed to a local branch you can pick it up?

Nah, for a small patchset, between branches and PRs, I prefer PRs. What I was saying is that there is not a single person here who "should" update master, so I would have preferred you did that before creating the PR to avoid all the polluting commits. But it's no big deal, really.

I'll pick this PR and upstream it next week, since I have a few more ACPI changes lined up, that I can slide this patch into.

**Comment by pbatard** [comment]
Since I have now [submitted this PR for review](https://edk2.groups.io/g/devel/message/56407), I will close it, as the rest of the review process will happen on the edk2-devel list.

**Pull request closed without merging**
